### ISSUE TITLE
Verdanturf GFX issues

### ISSUE THREAD

**Issue by apposada** [citrusbolt/pokeheliodor#23]
<img width="1044" alt="Captura de pantalla 2021-10-21 a las 20 55 18" src="https://user-images.githubusercontent.com/64602130/138528948-8e3c0858-d949-4394-8e31-bb54c4dc316b.png">
<img width="1044" alt="Captura de pantalla 2021-10-21 a las 20 55 29" src="https://user-images.githubusercontent.com/64602130/138528953-45026fa3-42c1-4ab4-95d9-c80935be5387.png">

**Comment by Jaizu** [comment]
Fixed.
