### ISSUE TITLE
Lilycove city GFX issues

### ISSUE THREAD

**Issue by apposada** [citrusbolt/pokeheliodor#37]
<img width="1044" alt="Captura de pantalla 2021-10-22 a las 0 00 20" src="https://user-images.githubusercontent.com/64602130/138529796-3ef64953-522e-4e1d-9ea7-dc2acfe91da7.png">

**Comment by Jaizu** [comment]
That was fixed. Leaving it opened anyway since it can be improved. 
![image](https://user-images.githubusercontent.com/18596778/139647085-96b7eace-fb5c-47a7-b631-3e0237318426.png)
