### ISSUE TITLE
Sealed Chamber GFX issues

### ISSUE THREAD

**Issue by apposada** [citrusbolt/pokeheliodor#38]
<img width="1044" alt="Captura de pantalla 2021-10-24 a las 23 29 53" src="https://user-images.githubusercontent.com/64602130/139528853-892859bf-df27-4f6d-844c-d8392a1d5ee6.png">
<img width="1044" alt="Captura de pantalla 2021-10-24 a las 23 29 59" src="https://user-images.githubusercontent.com/64602130/139528856-e3d153ca-2961-41b1-8afb-707b037f4e22.png">

**Comment by Jaizu** [comment]
Fixed!
