### ISSUE TITLE
Pokemon is said to be transferred even when there are empty slots in the party

### ISSUE THREAD

**Issue by malvarenga123** [citrusbolt/pokeheliodor#45]
At the beginning of the game, when your party is mostly empty. Every time you catch a pokemon, a message appears saying:

" was transferred to Lanette's PC.
It was placed in [FIRST POKEMON IN YOUR PARTY] box."

Notice that the name of the pokemon is just empty.

The pokemon is correctly put in your party and not in the PC.

**Comment by citrusbolt** [comment]
I can't seem to replicate this.  If it's happening consistently, can you send me your save file for investigation?  Feel free to DM me on Discord if you'd rather not have your save file be public.

**Comment by malvarenga123** [comment]
[heliodor20221106.zip](https://github.com/citrusbolt/pokeheliodor/files/10299439/heliodor20221106.zip)
Hi @citrusbolt, you can try with this fresh save.
Just go to the left and catch a pokemon.
This time Torchic leveled up and learned focus energy, so the message was:

"Focus energy was transferred to Lanette's PC.
It was placed in [TORCHIC] box."

**Comment by citrusbolt** [comment]
It should be fixed now.  Thanks for the help!
